<a href="https://colab.research.google.com/github/liangming1225/pythonclass/blob/master/python20220829.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20220829 python


## 資料型態
* int
* flaot
* bool
* str

In [29]:
z = 3>2
type(z)

bool

In [30]:
x1 = 4
y1 = 2


In [33]:
z1 = x1/y1
type(z1)

float

In [36]:
z2 = x1//y1
type(z2)

int

## 變數

In [ ]:
x = 1
_abc = 1
x = True
type(x)

bool

In [ ]:
a = [5,5,5,5]
a[0]
for i in range(4):
  a[i] = i + 1
a[2]

3

## Line Notify 使用簡介


* [取得權杖](https://notify-bot.line.me/en/)

!wget https://raw.githubusercontent.com/victorgau/khpy_linenotify_intro/main/py/linenotify.py

In [23]:
!wget https://raw.githubusercontent.com/victorgau/khpy_linenotify_intro/main/py/linenotify.py

--2022-08-29 03:54:53--  https://raw.githubusercontent.com/victorgau/khpy_linenotify_intro/main/py/linenotify.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 818 [text/plain]
Saving to: ‘linenotify.py’

linenotify.py       100%[===================>]     818  --.-KB/s    in 0s      

2022-08-29 03:54:53 (44.3 MB/s) - ‘linenotify.py’ saved [818/818]



In [24]:
from linenotify import Notify

In [26]:
token = "zrjRA5wwJQWMyEHFxYodb216uDR9SZ3WHa0PAkOKEJr"

In [27]:
Notify(token,"沒Token，借測試！",446,1988)

<Response [200]>

## 基本容器型別
* list 列表 []
* tuple 元組 ()
* dict 字典 {}
* set 集合 {}

In [87]:
a=['1aa',2,3,4,'5aa']
print(a[0])
type(a[0])
a[1:3]
a[1:]
a[:3]
a[-3:]
b = ('1aaa',2,3,4,'5aaa')
c = {'apple':10, 'banana':20, 'orange':30}
c['banana']
print(c['banana'])
d = {'a','b','c','d','e'}
e = {'c','d','f','g'}
d|e
f = list('abcde')
f

1aa
20


['a', 'b', 'c', 'd', 'e']

In [54]:
url = "https://uc.udn.com.tw/photo/2021/08/29/realtime/13631597.jpeg"

In [58]:
url[-13:]
url.split('/')[-1]

'13631597.jpeg'

In [69]:
f[1:-1]

['b', 'c', 'd']

In [80]:
f2 = tuple('abcde')
f2
f2.count('c')
f[2] = 123
f[2]

123

In [93]:
d = {}
type(dic)
e = set()
type(e)
d['dog'] = '狗狗'
d['cat'] = '貓貓'
d.keys()
d.values()
d.items()

dict_items([('dog', '狗狗'), ('cat', '貓貓')])

In [99]:
e1 = set('abcde')
e2 = set('cdefg')
e1
e2
print(e1 & e2)
print(e1 | e2)
print(e2-e1)

{'c', 'e', 'd'}
{'g', 'f', 'c', 'e', 'd', 'b', 'a'}
{'g', 'f'}


## 地圖
* folium
* geocoder

In [111]:
import folium
m = folium.Map(location=[45.5236, -122.6750])
m1 = folium.Map()
m2 = folium.Map(location=[22.6273, 120.3014])
m2 = folium.Map(location=[22.6273, 120.3014], zoom_start=16)
m2.save('高雄市.html')
folium.Marker([22.6273, 120.3014], popup="高雄市").add_to(m2)
m2

### 設定marker顏色

In [113]:
m2 = folium.Map(location=[22.6273, 120.3014], zoom_start=16)
folium.Marker([22.6273, 120.3014], popup="高雄市", icon=folium.Icon(color="red")).add_to(m2)
m2

In [ ]:
!pip install geocoder

In [132]:
import geocoder
place="中華電信"
g = geocoder.osm(place).latlng
m2 = folium.Map(location=g, zoom_start=16)
# m2.save('高雄市.html')
folium.Marker(g, popup=place, icon=folium.Icon(color="red")).add_to(m2)
m2

## 網頁爬蟲
* Crawling, requests selenium
* Parsing, BeautifulSoup
* [requests](https://requests.readthedocs.io/en/latest/)

### 抓取網頁原始碼

In [133]:
import requests

In [142]:
r = requests.get("https://victorgau.github.io/khpy_web_intro/html_only.html")
r.text

'<!DOCTYPE html>\n<html>\n<head>\n    <title>HTML範例</title>\n</head>\n<body>\n\n<h1>哈囉！HTML！</h1>\n\n<img src="ninja.jpg" />\n\n</body>\n</html>'

In [143]:
with open("test.html","w") as f:
  f.write(r.text)

### 使用BeautifulSoup解析網頁原始碼

In [147]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(r.text)
soup.h1.text

'哈囉！HTML！'

### 抓取圖片

In [149]:
url = "https://uc.udn.com.tw/photo/2021/08/29/realtime/13631597.jpeg"
filename = url.split('/')[-1]
r = requests.get(url)
with open(filename,"wb") as f:
  f.write(r.content)

### 抓PDF
* requests fake user agent

In [155]:
url = "https://arxiv.org/pdf/2208.12801.pdf"
filename = url.split("/")[-1]
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
r = requests.get(url, headers=headers)
with open(filename, "wb") as f:
  f.write(r.content)

### arxiv install

In [156]:
!pip install arxiv

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 81 kB 6.2 MB/s 
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6066 sha256=c3342235ded655ddf6a670c52403d7c6af3fc21309fa3ba3fec6a2a1a4c4b655
  Stored in directory: /root/.cache/pip/wheels/73/ad/a4/0dff4a6ef231fc0dfa12ffbac2a36cebfdddfe059f50e019aa
Successfully built sgmllib3k


In [158]:
import arxiv
search = arxiv.Search(
  query = "deep learning",
  max_results = 1,
  sort_by = arxiv.SortCriterion.SubmittedDate
)
search

arxiv.Search(query='deep learning', id_list=[], max_results=1, sort_by=<SortCriterion.SubmittedDate: 'submittedDate'>, sort_order=<SortOrder.Descending: 'descending'>)

### 條件式 if statements

``` python
if condition:
  code block
elif condition2:
  code block 2
else:
  others
``` 



In [1]:
a = 3
b = 2
if a > b:
  print ("a>b")
elif a < b:
  print("a<b")
else:
  print("a=b")

a>b


### 計算BMI並判斷體位, 數學式表示法latex equition
BMI算法：
$bmi = \frac{體重(公斤)}{身高(公尺)^2}$
$$bmi = \frac{體重(公斤)}{身高(公尺)^2}$$

|bmi|說明|
|:--|:--|
|<18.5|體重過輕|
|18.5 <= bmi < 24|健康體位|
|bmi >= 24|體重過重|


In [21]:
w = 67.7
h = 1.672
bmi = w/h**2
if bmi <18.5:
  print("體重過輕")
elif bmi > 24:
  print("體重過重")
else:
  print("健康體位")


體重過重


### 迴圈
* for loops
* while loops

``` python
for var in struct:
  code block
```

In [25]:
for i in range(3):
  print("block start:")
  print(i)
  print("block end:")

block start:
0
block end:
block start:
1
block end:
block start:
2
block end:


In [26]:
for i in range(3):
  print("block start:")
  print(i)
print("block end:")

block start:
0
block start:
1
block start:
2
block end:


In [29]:
x = list('abcde')
print(x)
for i in x:
  print(i)

['a', 'b', 'c', 'd', 'e']
a
b
c
d
e


In [41]:
fruits={'apple':20, 'orange':10, 'banana':20}
for i in fruits:
  print("default i=" + i)
  print("value=" + str(fruits[i]))
print("------")
for i in fruits.values():
  print(i)
print("------")
for i in fruits.keys():
  print(i)

default i=apple
value=20
default i=orange
value=10
default i=banana
value=20
------
20
10
20
------
apple
orange
banana


### json 格式

In [42]:
# 多行字串
s = """{
     "firstName": "John",
     "lastName": "Smith",
     "sex": "male",
     "age": 25,
     "address": 
     {
         "streetAddress": "21 2nd Street",
         "city": "New York",
         "state": "NY",
         "postalCode": "10021"
     },
     "phoneNumber": 
     [
         {
           "type": "home",
           "number": "212 555-1234"
         },
         {
           "type": "fax",
           "number": "646 555-4567"
         }
     ]
 }"""

In [43]:
type(s)

str

In [47]:
import json
data = json.loads(s)

In [60]:
data["phoneNumber"][-1]["number"]

'646 555-4567'

### 抓取台北市Younike 2.0 站點資料
https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json

In [ ]:
import requests
url = "https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json"
rs = requests.get(url).json()
type(rs)
print (rs[0])
for i in rs:
  print("站名:" + i["sna"].split("_")[1])
  print("經緯度:" + str(i["lat"]) + "," + str(i["lng"]))

### string formating

In [73]:
a = 1
b = 3.14159
c = True
d = 'dog'

In [74]:
"{} {} {} {}".format(a,b,c,d)

'1 3.14159 True dog'

In [75]:
"a={} b={} c={} d={}".format(a,b,c,d)

'a=1 b=3.14159 c=True d=dog'

In [76]:
"{0} {3} {2} {1}".format(a,b,c,d)

'1 dog True 3.14159'

### f-string

In [77]:
f"{a} {b} {c} {d}"

'1 3.14159 True dog'

In [ ]:
for i in rs:
  # s = f"站點名稱: {i['sna']} , GPS({i['lat']},{i['lng']})"
  print(f"站點名稱: {i['sna'].split('_')[-1]} , GPS({i['lat']},{i['lng']})")
  # print(f"站點名稱: {i}")

### 將Youbike2.0站點會至於地圖上


In [86]:
!pip install geocoder

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 98 kB 2.9 MB/s 


In [ ]:
import geocoder
import folium
city="台北市"
loc = geocoder.osm(city).latlng
map = folium.Map(loc, zoom_start=16)

for i in rs:
  folium.Marker((i['lat'], i['lng']), popup=i['sna'].split('_')[-1]).add_to(map)
map

### 劃金字塔

In [97]:
for i in range(5):
  print((5-i )*' '+ (2*i+1)*'*')

     *
    ***
   *****
  *******
 *********


### 函式

In [101]:
def pyramid(size):
  for i in range(size):
    print((size-i )*' '+ (2*i+1)*'*')
pyramid(10)

          *
         ***
        *****
       *******
      *********
     ***********
    *************
   ***************
  *****************
 *******************


### while

``` python
while condition:
  code block
```

In [ ]:
c = 10
while c > 0:
  print(c)
  c = c-1

### break, continue

In [ ]:
for i in range(10):
  if i == 5:
    break
  print(i)

### function return

In [112]:
def square1(x):
  print(2**x)
def square2(x):
  return 2**x
def square3(x):
  return None
print(square1(3))

8
None


### Exception handle
```python
try:
  程式區塊
except Exception as e:
  例外處理區塊
```

In [113]:
def add(a, b):
  print(f"{a} + {b} = {a+b}")

def sub(a, b):
  print(f"{a} - {b} = {a-b}")

def mul(a, b):
  print(f"{a} x {b} = {a*b}")

def div(a, b):
  print(f"{a} / {b} = {a/b}")


In [114]:
fns = [add, div, sub, mul]

In [ ]:
a = 1
b = 0
for fn in fns:
  fn(a,b)

In [117]:
a = 1
b = 0
for fn in fns:
  try:
    fn(a,b)
  except Exception as e:
    print(e.args)

1 + 0 = 1
('division by zero',)
1 - 0 = 1
1 x 0 = 0


## 資料分析簡介
* Numpy => Numerical Python => 科學運算套件
* MatPlotLib => Matrix Plotting Library => 繪圖套件
* Pandas => Panel Data => 資料分析基礎套件

載入慣例：
``` python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

## Numpy
* ndarray => N-Dimensional Array => 多維陣列
* ufunc => Unversal Functions => 通用函式

### ndarray

In [118]:
import numpy as np

In [119]:
x = [1,2,3]
y = [4,5,6]

In [120]:
x + y

[1, 2, 3, 4, 5, 6]

In [121]:
x *2

[1, 2, 3, 1, 2, 3]

In [123]:
x1 = np.array(x)
y1 = np.array(y)
x1 + y1

array([5, 7, 9])

In [124]:
x1 * 2

array([2, 4, 6])

### ufunc

In [125]:
import math

In [ ]:
math.sin(math.pi/2)

In [ ]:
math.sin(x)

In [129]:
np.sin(np.pi/2)

1.0

In [130]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
list(range(25))

In [132]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [133]:
data = np.arange(25)

In [134]:
data.dtype

dtype('int64')

In [135]:
data.shape

(25,)

In [136]:
data.size

25

In [137]:
data.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [142]:
data2 = data.reshape(5,5)
data2.shape
data2.size

25

### indexing & slicing

In [143]:
data2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [145]:
data2[2]

array([10, 11, 12, 13, 14])

In [144]:
data2[2][2]

12

#### get 6,7 & 11,12

In [147]:
data2[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [149]:
data2[2,2]

12

In [150]:
data2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])